### ISSUE TITLE
problem with istallation UBUNTU 18.10

### ISSUE THREAD

**Issue by Salvo107** [saferoom-app/saferoomlinux#4]
Hi, while I install your software the terminal give me this message when I try to processing: 
`python setup.py install 
`
why? thanks you for all.
this is the terminal's  error-message 
```
Salvatore@TY-OMEN:/tmp/evernote-sdk-python$ python setup.py 
  File "setup.py", line 22
    packages=find_packages('lib',exclude=["*.thrift", "*.thrift.*", "thrift.*", "thrift"]),
SyntaxError: keyword argument repeated

```

**Comment by saferoombiz** [comment]
Hi, @Salvo107 
I haven't tried to install on this Ubuntu 18.10. Let me install the Ubuntu 18.10 and check it. 

BR,
Alexey
